project:
  type: website
  resources:
    - data/*
    - styles.css
  output-dir: docs

website:
  open-graph:
    image: eurocim-icon.gif
  image: eurocim-icon.gif
  favicon: "eurocim-icon.gif"
  title: "European Causal Inference Meeting"
  navbar: 
    background: "#07342a"
    left:
      - text: "Home"
        href: index.qmd
      - past-conferences.qmd
      - steering-committee.qmd
  page-footer:
    background: "#07342a"
    left:
      - text: "Contact webmaster"
        href: "mailto:european.cim@gmail.com"
    right:
      - text: ""

format:
    html:
      page-layout: full
      title-block-banner: "#07342a"
      theme: 
        - sandstone
        - custom.scss
      css: styles.css
      toc: false
      background: "#07342a"
      logo: "eurocim-icon.gif"


